environment:
  global:
    CHANS_DEV: "-c pyviz/label/dev -c conda-forge"
  matrix:
    - PY: "2.7"
      CONDA: "C:\\Miniconda-x64"
    - PY: "3.6"
      CONDA: "C:\\Miniconda36-x64"

matrix:
  allow_failures:
    - PY: "2.7"
    - PY: "3.6"

install:
  - "SET PATH=%CONDA%;%CONDA%\\Scripts;%PATH%"
  - "conda install -y -c pyviz pyctdev && doit ecosystem_setup"
  - "doit env_create %CHANS_DEV% --name=test --python=%PY%"
  - "activate test"
  - "doit develop_install %CHANS_DEV% -o recommended"
  - "doit env_capture"

build: off
skip_branch_with_pr: true  # only do one run per commit
clone_depth: 5
skip_tags: true

test_script:
  - "bokeh sampledata"
  - "doit test_all_recommended"
