name: hvplot
channels:
  - pyviz
  - intake
  - defaults
dependencies:
  #
  # Versions for holoviz packages pinned to ensure mutual compatibility
  #
  - bokeh::bokeh=0.13.0
  - pyviz::holoviews=1.10.6
  - datashader=0.6.6
  - param=1.6.1
  #
  # Direct dependencies for package installation
  #
  - yaml
  - requests
  #
  # Direct dependencies of most or all the tutorials
  #
  - python>=3.6,<3.7 # Pinned in case of unknown future or past compatibility issues
  - ipython=5        # Pinned to avoid tab-completion issue in ipython=6
  - numpy=1.13       # Pinned to avoid warnings with numpy=1.14 and bokeh=1.12.14
  - notebook>=5.4    # Pinned to avoid rate limiting for large images with notebook=5.0
  - dask=0.17.1      # Pinned in case of future API changes
  - jupyter
  - pandas
  - xarray
  - scipy
  #
  # Directly imported dependencies of certain specialized tutorials
  #
  - streamz=0.3.0
  #
  # Indirect dependencies of our direct dependencies
  #
  - conda-forge::selenium=3.3.1   # Required for exporting Bokeh plots to PNG
  - phantomjs=2.1.1  # Required for exporting Bokeh plots to PNG
  - netcdf4          # Required for reading .nc files
  - fastparquet      # Required for reading Parquet files
  - python-snappy    # Required for reading snappy-compressed Parquet files
  - pytest>=3.2      # Required by? Pinned to avoid installation problems on Windows with 3.1?
  - cffi             # Unstated dependency of fastparquet?
  - tornado=4.5.3    # Required for Jupyter notebook and bokeh server
  # Intake data packages used in documentation #
  - intake::airline_flights
  - intake::us_crime
  - intake::intake
  - intake::intake-parquet
  - boto3=1.4.7
  - colorcet>=2
